<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-BlazorAppIdentity-b4178170-a728-4aad-a79b-2f102096cce0</UserSecretsId>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BlazorAppIdentity.Client\BlazorAppIdentity.Client.csproj"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\Migrations\" />
      <Folder Include="Migrations\" />
      <Folder Include="wwwroot\images\" />
    </ItemGroup>

</Project>
