<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorCookBoop.App.Client\BlazorCookBoop.App.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.14" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Recipe03\Offer.razor" />
    <_ContentIncludedByDefault Remove="Recipe03\Ticket.razor" />
  </ItemGroup>

</Project>
