<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-BlazorFluentDemo-a3ad1368-600e-4900-a905-774fa397add7</UserSecretsId>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <None Update="Data\app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BlazorFluentDemo.Client\BlazorFluentDemo.Client.csproj"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.13.2"/>
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.13.2"/>
    </ItemGroup>
</Project>
