// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudBlazorBolos.Data;

#nullable disable

namespace MudBlazorBolos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MudBlazorBolos.Data.Bolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Bolos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Um bolo tipico português",
                            ImagemUrl = "https://www.rissolariatradicional.com/wp-content/uploads/2020/11/1-Pastel-de-Nata-centrado.jpg",
                            Nome = "Pastel de Nata",
                            Preco = 3.5m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Um bolo tipico frances",
                            ImagemUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2a/Croissant-Petr_Kratochvil.jpg",
                            Nome = "Croissant",
                            Preco = 7.5m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Um bolo tipico de felgueiras",
                            ImagemUrl = "https://merceariadeportugal.com/cdn/shop/products/PAO_DE_LO_INDIVIDUAL_800x.png",
                            Nome = "Pão de ló",
                            Preco = 17.5m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Um bolo tipico português",
                            ImagemUrl = "https://www.fabricoproprio.net/c/wp-content/uploads/2022/11/38_jesuita.jpg",
                            Nome = "Jesuíta",
                            Preco = 17.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
