<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.13.2"/>
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.13.2"/>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.EntityFrameworkCore">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\microsoft.entityframeworkcore\10.0.0\lib\net10.0\Microsoft.EntityFrameworkCore.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
