<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.12.0" />
    <ProjectReference Include="../BlazorTarefas.Shared/BlazorTarefas.Shared.csproj" />
    <ProjectReference Include="../BlazorTarefas.Client/BlazorTarefas.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.8" />
  </ItemGroup>

</Project>
