// <auto-generated />
using BlazorFluentCRUD.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorFluentCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209163817_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BlazorFluentCRUD.Context.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "lfilipecosta3@gmail.com",
                            Foto = "/fotos/profile.jpg",
                            Idade = 31,
                            Nome = "Luis"
                        },
                        new
                        {
                            Id = 2,
                            Email = "johnlennon@ceu.net",
                            Foto = "/fotos/profile-lennon.jpg",
                            Idade = 31,
                            Nome = "John Lennon"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ozzy@ceu.net",
                            Foto = "/fotos/profile-ozzy.jpg",
                            Idade = 78,
                            Nome = "Ozzy"
                        },
                        new
                        {
                            Id = 4,
                            Email = "amy@ceu.net",
                            Foto = "/fotos/profile-amy.jpg",
                            Idade = 27,
                            Nome = "Amy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
